=== fishballapp/linkz/public/config-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "description": "A field for the [JSON schema](https://json-schema.org/) specification",
      "type": "string"
    },
    "outDir": {
      "type": "string",
      "description": "Path to the output directory."
    },
    "publicDir": {
      "type": "string",
      "description": "Path to the output directory."
    },
    "favicon": {
      "type": "string",
      "description": "URL or path to the favicon. (Note: path would be relative from `publicDir`)"
    },
    "profilePicture": {
      "type": "string",
      "description": "URL or path to the profile picture. (Note: path would be relative from `publicDir`)"
    },
    "name": {
      "type": "string",
      "description": "Name of the user."
    },
    "links": {
      "type": "array",
      "description": "A list of links associated with the user.",
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Title of the link."
          },
          "url": {
            "type": "string",
            "format": "uri",
            "description": "URL of the link."
          }
        },
        "required": ["title", "url"],
        "additionalProperties": false
      }
    }
  },
  "required": ["outDir", "profilePicture", "name", "links"],
  "additionalProperties": false
}

=== fishballapp/linkz/linkz.config.json
{
  "$schema": "https://linkz.fishball.app/config-schema.json",
  "outDir": "dist",
  "publicDir": "public",
  "favicon": "logo.png",
  "profilePicture": "logo.png",
  "name": "Linkz",
  "links": [
    {
      "title": "Github",
      "url": "https://github.com/fishballapp/linkz"
    },
    {
      "title": "JSR",
      "url": "https://jsr.io/@fishballpkg/linkz"
    }
  ]
}
